#! /usr/bin/env python
# pgt_comm
# This is part of python_gnuplot_tools
# Hanno Rein 2011
#
# Calculates commulative distribution
#
import sys, math
from operator import itemgetter

if len(sys.argv)<2:
	print "Usage: pgt_maxn [filename] n"
	sys.exit(0)

if len(sys.argv)>2:
	filename 	= sys.argv[1]
	n 		= int(sys.argv[2])
	f 		= open(filename)
else:
	f 		= sys.stdin
	n 		= int(sys.argv[1])
		


# Read data
data = []
for line in f:
	value = line.split()[n];
	data.append(value)

data.sort(key=float)

counter = 0
for i in data:
	counter += 1
	print i,counter
