#! /usr/bin/env python
# pgt_fraction
# This is part of python_gnuplot_tools
# Hanno Rein 2011
#
# Outputs a fraction of the lines.
#
import sys, math
from operator import itemgetter

if len(sys.argv)<2:
	print "Usage: pgt_fraction [filename] fraction"
	sys.exit(0)

if len(sys.argv)>2:
	filename 	= sys.argv[1]
	fraction	= float(sys.argv[2])
	f 		= open(filename)
else:
	f 		= sys.stdin
	fraction	= float(sys.argv[1])
		


# Read data
data = []
m = 0
for line in f:
	data.append(line)
	m = m + 1

n=int(m*fraction)
for i in range(n):
	index = int(math.floor(i*float(m)/float(n)))
	print data[index],
